name: dependency_override
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  domain:
    path: ../domain
  infrastructure_firebase:
    path: ../infrastructure/firebase
  infrastructure_mock:
    path: ../infrastructure/mock
  infrastructure_shared_preferences:
    path: ../infrastructure/shared_preferences
  riverpod: ^3.1.0

resolution: workspace
