name: infrastructure_{{package_name.snakeCase()}}
description: "This package provides {{package_name.snakeCase()}}."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.1
  flutter: ^3.27.1

dependencies:
  collection:
  core:
    path: ../../core
  freezed_annotation:
  riverpod:
  riverpod_annotation:

dev_dependencies:
  build_runner:
  custom_lint:
  freezed: ^2.4.7
  json_serializable:
  riverpod_generator:

resolution: workspace
