name: infrastructure_firebase
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  cloud_firestore: null
  cloud_functions: null
  collection: null
  domain:
    path: ../../domain
  firebase_analytics: null
  firebase_app_check: null
  firebase_auth: null
  firebase_core: null
  firebase_crashlytics: null
  firebase_remote_config: null
  firebase_storage: null
  flutter:
    sdk: flutter
  freezed_annotation: null
  google_sign_in: null
  json_annotation: null
  riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.4
  flutter_test:
    sdk: flutter
  json_serializable: null

  riverpod_generator: ^4.0.0

  test: any

resolution: workspace
