name: designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  adaptive_dialog: ^2.4.0
  animations: null
  collection: null
  domain:
    path: ../domain
  dynamic_color: null
  flutter:
    sdk: flutter
  flutter_hooks: null
  flutter_svg: null
  freezed_annotation: null
  gap: null
  gauge_indicator: null
  hooks_riverpod: ^3.1.0
  linked_scroll_controller: null
  material_color_utilities: null
  nested: null
  responsive_framework: ^1.5.1
  riverpod_annotation: ^4.0.0
  shimmer: null
  slang: ^4.11.1
  slang_flutter: ^4.11.0
  sliver_tools: null
  store_redirect: ^2.0.3
  theme_tailor_annotation: null
  url_launcher: null

dev_dependencies:
  build_runner: ^2.10.4

  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  freezed: any

  riverpod_generator: ^4.0.0

  slang_build_runner: ^4.1.0
  theme_tailor: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true

resolution: workspace
