name: infrastructure_shared_preferences
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  collection: any
  domain:
    path: ../../domain
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: null

dev_dependencies:
  build_runner: ^2.4.14

  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.6.1

  test: any

resolution: workspace
