name: infrastructure_shared_preferences
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  collection: any
  domain:
    path: ../../domain
  flutter:
    sdk: flutter
  riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  shared_preferences: null

dev_dependencies:
  build_runner: ^2.10.4

  flutter_test:
    sdk: flutter

  riverpod_generator: ^4.0.0

  test: any

resolution: workspace
