name: packages_foundation
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  logger: any
  riverpod: ^3.1.0
  uuid: ^4.5.2

resolution: workspace
