name: infrastructure_mock
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.4

dependencies:
  clock: ^1.1.1
  collection: any
  domain:
    path: ../../domain
  riverpod: ^2.6.1

dev_dependencies:
  nilts: any
  pedantic_mono: null

resolution: workspace
