name: domain
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  freezed_annotation: null
  intl: null
  json_annotation: null
  logger: null
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  version: null

dev_dependencies:
  build_runner: ^2.4.14

  freezed: null
  json_serializable: null

  riverpod_generator: ^2.6.1

resolution: workspace
