name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  adaptive_dialog: ^2.4.0
  animated_to: ^0.2.0
  cupertino_icons: null
  dependency_override:
    path: ../../packages/dependency_override
  designsystem:
    path: ../../packages/designsystem
  device_preview: ^1.2.0
  domain:
    path: ../../packages/domain
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_hooks: any
  flutter_localizations:
    sdk: flutter
  flutter_settings_ui: ^3.0.1
  freezed_annotation: any
  gap: any
  go_router: any
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: any
  material_design_icons_flutter: ^7.0.7296
  nested: null
  package_info_plus: ^8.2.1
  riverpod_annotation: ^2.6.1
  settings_ui: ^2.0.2
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  version: null

dev_dependencies:
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  custom_lint: ^0.7.0
  flutter_gen: ^5.8.0
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  go_router_builder: ^2.4.1
  icons_launcher: any
  json_serializable: any
  nilts: any
  pedantic_mono: any
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true

  # Assets & Fonts
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true

resolution: workspace
